name: Deploy

on:
  push:
    branches: [ dev, main ]
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
