name: Deploy Prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Prod
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: gentle-gorge-10023
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
